### ISSUE TITLE
Issues with the "cancel" button after taking either Fly actions

### ISSUE THREAD

**Issue by GabeValentine** [blistik/FireflyKalidasa#2]
These events are erroneously triggered when a player selects "cancel" after selecting a movement action (Mosey or Full Burn):
- Drawing a nav card
- Alert token resolution
- Alliance/Reaver Contact resolution

**Comment by blistik** [comment]
I only saw this issue report after releasing v1.9.7.    There was some work on the triggering of these items when refreshing the Actions panel (which occurs after any button press).  I have been unable to replicate the issue in the current version. The image below shows at the start of a turn where the Cruiser has already been faced in the previous turn. A token exists (set by another player) between turns. Pressing Mosey, then Cancel Action does not trigger a Cruiser Contact, nor a Nav Card, nor processes the Alert which is as expected.
![Image1](https://github.com/blistik/FireflyKalidasa/assets/48114592/d208888e-faae-4bfd-a1a3-8f78dc8536db)

Can you re-test and report if the issue remains.  If so, can you provide step by step details on how to replicate the issue.  thanks.

**Comment by blistik** [comment]
no further reports on this issue, closing it out.
